import React, { useState } from 'react';
import type { PublicMarket, PublicOverview } from '../../packages/shared/public.js';
import { Allocation, Empty, Icon, Skeleton } from './components.js';
import { AssetDialog, Avatar } from './market.js';
import { dateTime, eligibilityLabel, money, short, units } from './view-model.js';

function FeeFlow() {
  return <section className="fee-flow" aria-label="Proposed fee flow, not active rewards">
    <div className="flow-end"><span className="flow-icon"><Icon name="rewards" /></span><div><span className="step-caption">01 / RECEIVE</span><h3>Creator fees</h3><p>Only what is actually received</p></div></div><span className="flow-arrow" aria-hidden="true"><Icon name="arrow" /></span>
    <div className="flow-budget"><div className="flow-budget-label"><span className="step-caption">02 / PURCHASE</span><h3>Ten equal budgets</h3></div><div className="budget-cells" role="img" aria-label="Ten purchase budgets, each 10 percent of the basket budget">{Array.from({ length: 10 }, (_, i) => <span key={i} aria-hidden="true"><i>{String(i + 1).padStart(2, '0')}</i><b>10<small>%</small></b></span>)}</div></div><span className="flow-arrow" aria-hidden="true"><Icon name="arrow" /></span>
    <div className="flow-end"><span className="flow-icon"><Icon name="wallet" /></span><div><span className="step-caption">03 / CREDIT</span><h3>Eligible holders</h3><p>By verified snapshot balance</p></div></div>
  </section>;
}
export function Homepage({ data, loading, error, retry }: { data?: PublicOverview; loading: boolean; error: string; retry: () => void }) {
  const [detail, setDetail] = useState<{ asset: PublicMarket; snapshot: PublicOverview }>();
  const observations = data?.markets.filter(asset => asset.rank !== null).slice(0, 10) ?? [];
  const prelaunch = data?.project.phase === 'prelaunch';
  return <>
    <section className="hero"><div className="hero-orbit" aria-hidden="true"><span /><span /><span /></div><div className="hero-copy"><div className="eyebrow accent">A little more of the Ember ecosystem</div><h1>One Ember holding.<span>Ten possibilities.</span></h1><p className="hero-description">A proposed reward basket of ten leading Ember assets, funded by received creator fees and shared with eligible EMBER10 holders.</p>
      <p className="launch-note"><i className="dot" />{prelaunch ? 'Prelaunch — rewards are not active yet.' : 'Confirming project readiness. Rewards are not active.'}</p>
      <div className="hero-actions"><a className="btn primary" href="#basket">Explore the ten <Icon name="arrow" /></a><a className="btn ghost" href="#how">How it works <Icon name="external" /></a></div>
      <a className="qualification" href="#wallet"><Icon name="transparency" /><span><strong>{data ? `${units(data.policy.holderUnits, 0)} EMBER10` : loading ? 'Loading balance requirement' : 'Balance requirement unavailable'}</strong>{data && ' snapshot threshold'}<span className="qualification-link">View eligibility rules ↗</span></span></a>
      <a className="hero-readiness" href="#transparency">{data ? `${data.selection.selectedCount}/10 assets selected · ${data.fundedBasket.status === 'funded' ? 'Funded round recorded' : data.fundedBasket.status === 'none' ? 'No funded round' : 'Funded basket unavailable'}` : loading ? 'Loading current project readiness' : 'Project readiness unavailable'} <Icon name="arrow" /></a>
      </div><div className="hero-seal" aria-hidden="true"><div className="seal-top">THE EMBER COLLECTION</div><span className="seal-number">10</span><div className="seal-grid">{Array.from({ length: 10 }, (_, i) => <i key={i} />)}</div><span className="seal-bottom">EQUAL BUDGETS. SHARED POSSIBILITY.</span></div></section>
    <FeeFlow />
    <section className="observations" aria-labelledby="observations-title"><div className="section-heading"><div><div className="eyebrow accent">Explore the ecosystem</div><h2 id="observations-title">Ten in the spotlight.</h2><p>The ten highest ranked observations in the current Ember catalogue.<br className="desktop-break" /> These are market observations, not a selected or funded reward basket.</p></div><a className="btn small" href="#basket">Full market explorer <Icon name="arrow" /></a></div><div className="preview-source"><span><i className="dot" />{data?.discovery.status === 'stale' ? 'Stale observations' : data?.discovery.status === 'warming' ? 'Incomplete observations' : data?.discovery.status === 'unavailable' ? 'Source unavailable' : data ? 'Ember catalogue observations' : loading ? 'Loading Ember observations' : 'Source unavailable'}</span>{data?.discovery.fetchedAt && <span>Fetched {dateTime(data.discovery.fetchedAt)}</span>}</div>
      {loading && data && <p className="preview-refresh" role="status">Refreshing observations. The previous fetch remains visible until the request completes.</p>}
      {data?.discovery.status === 'stale' && <p className="preview-notice" role="status">Showing the last successful observation. Ranking may have changed; new purchases remain blocked.</p>}{data?.discovery.status === 'warming' && <p className="preview-notice" role="status">The source catalogue is incomplete. These observations do not establish a complete ranking or an eligible basket.</p>}
      {loading && !data ? <div className="preview-loading"><Skeleton /></div> : !observations.length ? <div className="panel"><Empty title={data?.discovery.status === 'unavailable' || !data ? 'Market observations are unavailable.' : 'No ranked observations yet.'} text={data?.discovery.message || error || 'No replacement assets are shown while we verify the source.'}><button className="btn" onClick={retry}>Try again</button></Empty></div> : <div className="asset-preview-grid">{observations.map(asset => <button className="asset-preview-card" key={asset.mint} onClick={() => data && setDetail({ asset, snapshot: data })} aria-label={`Details for ${asset.symbol}, mint ${asset.mint}`}><span className="asset-card-top"><Avatar asset={asset} /><span className="card-rank">#{String(asset.rank).padStart(2, '0')}</span></span><span className="card-symbol">{asset.symbol}</span><span className="card-name">{asset.name || 'Name not reported'}</span><span className="token-mint">{short(asset.mint)}</span><span className="card-cap"><small>Observed market cap</small><strong>{money(asset.marketCapUsd)}</strong></span><span className="card-bottom"><span className="status-small">{eligibilityLabel(asset)}</span><span className="card-detail">Details <Icon name="arrow" /></span></span></button>)}</div>}<p className="preview-footnote">Mint addresses identify assets. Market caps are Ember-reported USD observations; supply basis is undocumented.</p>
    </section>
    <section className="readiness-section" aria-labelledby="readiness-title"><div className="readiness-intro"><div className="eyebrow accent">Where things stand</div><h2 id="readiness-title">Built on checks. <br />Ready on evidence.</h2><p>Real market observations are a start. Verified assets, a funded round and connected reward records are separate requirements.</p><a className="link-inline" href="#transparency">View current readiness <Icon name="arrow" /></a></div><div className="readiness-list"><div><span className="readiness-icon"><Icon name="transparency" /></span><div><h3>Asset eligibility</h3><p>{data ? data.selection.selectedCount === 10 ? 'Selection recorded; funding is a separate step.' : 'All ten must pass the published policy before new purchases.' : loading ? 'Loading the current selection policy.' : 'The selection policy could not be fetched.'}</p></div><strong>{data ? `${data.selection.selectedCount}/10` : loading ? 'Pending' : 'Unavailable'}</strong></div><div><span className="readiness-icon"><Icon name="basket" /></span><div><h3>Funded basket</h3><p>{data?.fundedBasket.status === 'funded' ? 'Membership is fixed to its funded round.' : 'No funded round is available to inspect.'}</p></div><strong>{data ? data.fundedBasket.status === 'funded' ? 'Recorded' : data.fundedBasket.status === 'none' ? 'Not funded' : 'Unavailable' : loading ? 'Pending' : 'Unavailable'}</strong></div><div><span className="readiness-icon"><Icon name="wallet" /></span><div><h3>Reward accounting</h3><p>Unknown amounts are never presented as zero. <a href="#wallet">Check record availability</a></p></div><strong>{data ? 'Unreported' : loading ? 'Pending' : 'Unavailable'}</strong></div></div></section>
    <section className="home-rules"><div className="section-heading"><div><div className="eyebrow accent">Simple split. Visible rules.</div><h2>Every fee has a purpose.</h2><p>The allocation applies after bounded direct execution costs.</p></div><a className="link-inline" href="#how">Follow the process <Icon name="arrow" /></a></div><div className="lower-grid"><Allocation /><article className="panel home-steps"><ol>{[['Receive', 'Only verified creator fees enter the allocation.'], ['Purchase', 'Ten eligible assets get equal purchase budgets.'], ['Credit', 'Actual acquired units are shared by eligible snapshot balance.']].map(([title, text], i) => <li key={title}><span>{String(i + 1).padStart(2, '0')}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol><a className="link-inline" href="#transparency">Developer accounting & complete rules <Icon name="arrow" /></a></article></div></section>
    {detail && <AssetDialog asset={detail.asset} data={detail.snapshot} onClose={() => setDetail(undefined)} />}
  </>;
}
