import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
type Data=Record<string,any>;
async function api(path:string){const r=await fetch('/api/'+path,{headers:{accept:'application/json'}});const body=await r.json();if(!r.ok)throw Error(body.message??'Service unavailable. Please try again.');return body;}
const short=(v:string)=>v.slice(0,5)+'…'+v.slice(-5);
function units(value:string|undefined,decimals=6){if(value===undefined)return '—';const v=BigInt(value),scale=10n**BigInt(decimals),whole=v/scale,fraction=(v%scale).toString().padStart(decimals,'0').replace(/0+$/,'');return whole.toLocaleString()+(fraction?'.'+fraction:'');}
const time=(v:string|number|undefined)=>v?new Date(v).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'UTC'})+' UTC':'Not available';
function Icon({name}:{name:string}){const paths:Record<string,React.ReactNode>={basket:<><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><path d="M14 17h7m-3.5-3.5v7"/></>,rewards:<><path d="M3 18l5-6 5 3 8-11M3 21h18"/></>,wallet:<><rect x="3" y="5" width="18" height="15" rx="2"/><path d="M3 8h18M16 12h5v5h-5z"/></>,transparency:<><path d="M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6zM8 12l3 3 5-6"/></>};return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true">{paths[name]}</svg>}
function App(){const [tab,setTab]=useState(location.hash.slice(1)||'basket');const [data,setData]=useState<Data>();const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [wallet,setWallet]=useState('');const [lookup,setLookup]=useState<Data>();const [lookupError,setLookupError]=useState('');const [searching,setSearching]=useState(false);const [epoch,setEpoch]=useState<Data>();const [copied,setCopied]=useState(false);
 async function reload(){try{const [status,project,basket,transparency,epochs]=await Promise.all(['status','project','basket','transparency','epochs'].map(api));setData({status,project,basket,transparency,epochs});setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{reload();const id=setInterval(reload,60000);return ()=>clearInterval(id);},[]);
 function navigate(t:string){setTab(t);location.hash=t;setEpoch(undefined);window.scrollTo({top:0});}
 useEffect(()=>{const f=()=>setTab(location.hash.slice(1)||'basket');addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f);},[]);
 async function search(e:React.FormEvent){e.preventDefault();setSearching(true);setLookup(undefined);setLookupError('');try{setLookup(await api('wallets/'+encodeURIComponent(wallet.trim())+'/rewards'));}catch(e){setLookupError((e as Error).message);}finally{setSearching(false);}}
 const s=data?.status,p=data?.project,b=data?.basket,t=data?.transparency;const demo=s?.mode==='demo',isTest=demo||s?.mode==='test';
 const names:Record<string,string>={basket:'The Five',rewards:'Rewards',wallet:'My Rewards',transparency:'Transparency'};
 const symbol=(mint:string)=>t?.assets.find((a:Data)=>a.mint===mint)?.symbol??short(mint);
 const decimals=(mint:string)=>t?.assets.find((a:Data)=>a.mint===mint)?.decimals??6;
 function receiptLink(result:Data){if(!result?.signature)return null;if(isTest&&demo)return <span className="muted">Simulated receipt · {short(result.signature)}</span>;const cluster=s?.cluster==='mainnet-beta'?'':`?cluster=${s?.cluster==='localnet'?'custom&customUrl='+encodeURIComponent('http://127.0.0.1:8899'):'devnet'}`;return <a href={'https://explorer.solana.com/tx/'+result.signature+cluster} target="_blank" rel="noreferrer">View transaction ↗</a>;}
 return <div className="shell"><aside><a className="brand" href="#basket" onClick={()=>navigate('basket')} aria-label="EMBER5 home"><span className="mark">E</span>EMBER<span className="brand-five">5</span></a><div className="workspace-label">REWARD OBSERVATORY</div><nav aria-label="Main navigation">{Object.entries(names).map(([key,label])=><button key={key} className={tab===key?'nav-item active':'nav-item'} onClick={()=>navigate(key)}><Icon name={key}/>{label}{key==='basket'&&<span className="nav-count">05</span>}</button>)}</nav><div className="sidebar-bottom"><div className="network"><span className="square"/>{s?.mode==='prelaunch'?'PRELAUNCH':s?.mode?.toUpperCase()??'CONNECTING'}</div><p>Independent by design.<br/>Transparent by default.</p><a href="#transparency" onClick={()=>navigate('transparency')}>Inspect the rules <span>↗</span></a><div className="version">WORKING NAME · PILOT v0.1</div></div></aside>
 <main><header className="topbar"><div><span className="breadcrumb">EMBER5</span><span className="slash">/</span>{names[tab]??'The Five'}</div><div className="header-status"><span className={'badge '+(isTest?'orange':'')}>{isTest?s.mode.toUpperCase()+' · TEST DATA':s?.mode==='live'?'LIVE PILOT':'PRELAUNCH'}</span><span className="utc">ALL TIMES UTC</span></div></header>
 <div className="content">{isTest&&<div className="notice demo">{s.hostedSnapshot?'RECORDED DEMO — Historical synthetic data. No settlement worker or blockchain broadcasts.':demo?'DEMO — Synthetic purchases and receipts. No blockchain broadcasts.':'TEST CHAIN — Test mints and simulated swap liquidity. No mainnet funds.'}</div>}
 {error&&<div className="notice error" role="alert"><strong>Data connection unavailable.</strong> {error}<button className="text-button" onClick={reload}>Retry</button></div>}
 {loading?<div className="loading" role="status"><div className="loader"/>Connecting to the reward ledger…</div>:data&&<>
 {tab==='basket'&&<><section className="page-heading"><div className="eyebrow">ONE TOKEN. FIVE REWARD ASSETS.</div><div className="heading-row"><div><h1>The five, in view<span>.</span></h1><p>Hold EMBER5. Receive the Ember five.</p></div><div className="phase-tag"><span className="status-ring"/>{b.ready?'Basket selected':'Awaiting launch'}</div></div></section>
 <div className="identity"><div><span className="small-label">{demo?'DEMO MINT: NOT DEPLOYED':'CANONICAL MINT'}</span><strong>{p.mint?p.mint:'Contract not deployed'}</strong></div>{p.mint?<button className="quiet-button" onClick={async()=>{await navigator.clipboard.writeText(p.mint);setCopied(true);setTimeout(()=>setCopied(false),2000);}}>{copied?'Copied':'Copy address'}</button>:<span className="muted">Buy link available after verification</span>}</div>
 <div className="section-title"><h2>The basket <span className="count">{b.selected.length}/5</span></h2><span className="muted">Equal purchase budgets · 20% each</span></div>
 {b.stale&&<div className="notice">This basket is historical. New purchases await a fresh verified selection.</div>}
 <section className="five-grid">{Array.from({length:5},(_,k)=>{const a=b.selected[k];return <article className={'asset-card '+(a?'filled':'empty')} key={k}><div className="asset-top"><span className="slot">0{k+1}</span><span className="asset-weight">20<span>%</span></span></div><div className={'asset-symbol color-'+k}>{a?a.symbol.slice(0,2):'—'}</div><h3>{a?a.symbol:'Awaiting selection'}</h3><p>{a?'Verified for this basket version':'An eligible Ember asset'}</p><div className="asset-divider"/>{a?<><span className="status-text">{isTest?'SYNTHETIC ELIGIBILITY':'ELIGIBLE'}</span><details><summary>Why this asset?</summary><p>Graduated · authority checks passed · complete owner coverage · viable route</p><p>Source: {a.source}</p><code>{a.mint}</code></details></>:<span className="status-text">NOT YET ACTIVE</span>}</article>;})}</section>
 <div className="basket-foot"><span>Basket freezes daily at 00:00 UTC. Changes affect future purchases.</span><span>{b.createdAt?'Selected '+time(b.createdAt):'First selection pending'}</span></div>
 <section className="lower-grid"><article className="flow-panel"><div className="eyebrow">HOW RECEIVED FEES ARE USED</div><h2>A clear path from fees to rewards.</h2><div className="allocation-bar"><span/><span/><span/></div><div className="split-legend"><div><b>80<span>%</span></b><span><i className="dot orange-dot"/> Basket rewards</span></div><div><b>10<span>%</span></b><span><i className="dot light-dot"/> Buyback & burn</span></div><div><b>10<span>%</span></b><span><i className="dot gray-dot"/> Operations</span></div></div><p className="muted">Applied to new creator revenue after bounded direct costs. Each basket asset receives an equal purchase budget.</p></article><article className="state-panel"><div className="eyebrow">REWARD ENGINE</div><div className="engine-title"><span className="status-ring"/><h2>{b.ready?'Accounting in view':'Waiting for funding'}</h2></div><p>{s.waitingReason}</p><dl><div><dt>Evaluation target</dt><dd>Every hour</dd></div><div><dt>Minimum basket budget</dt><dd>$25</dd></div><div><dt>Holder threshold</dt><dd>100,000 EMBER5</dd></div></dl><button className="text-button" onClick={()=>navigate('rewards')}>Explore reward status <span>↗</span></button></article></section>
 <section className="candidates"><div className="section-title"><h2>Live discovery</h2><span className="badge">SEPARATE FROM THE FUNDED BASKET</span></div><p className="muted">Public market observations require further verification before they can enter the five.</p>{s.discovery?.candidates?.length?<><div className="table-wrap"><table><thead><tr><th>ASSET</th><th>REPORTED MARKET CAP</th><th>GRADUATED</th><th>SELECTION STATUS</th></tr></thead><tbody>{s.discovery.candidates.slice(0,5).map((c:Data)=><tr key={c.mint}><td><strong>{c.symbol}</strong><small>{short(c.mint)}</small></td><td>{c.reportedMarketCapUsd==null?'Unavailable':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(c.reportedMarketCapUsd)}<small>Supply basis unverified</small></td><td>{c.graduated?'Yes':'No'}</td><td><span className="badge">UNVERIFIED</span></td></tr>)}</tbody></table></div><p className="source-line">Source: Ember public catalogue · {time(s.discovery.at)} {s.discoveryStale?'· STALE':''}</p></>:<div className="empty-inline">No verified live market observations available yet. Discovery does not change recorded basket membership.</div>}</section></>}
 {tab==='rewards'&&<><section className="page-heading"><div className="eyebrow">RECEIVED. ACQUIRED. CREDITED. DELIVERED.</div><h1>Follow every reward<span>.</span></h1><p>A credit is an obligation. A delivery is a finalized transfer.</p></section><div className="metrics"><article><span>Verified creator fees received</span><b>{units(t.receivedLamports,9)} <small>SOL</small></b><p>{demo?'Synthetic funding only':'Finalized, attributed receipts only'}</p></article><article><span>Finalized payout transactions</span><b>{t.finalizedPayoutTransactions}</b><p>One transaction may contain multiple transfers</p></article><article><span>Next evaluation</span><b className="text-metric">{s.nextEvaluation?time(s.nextEvaluation):'Waiting'}</b><p>No newly received fees means no new budget</p></article></div>
 <div className="section-title"><h2>Accrued & delivered</h2><span className="muted">Exact asset units · no estimated USD totals</span></div>{t.accrued.length?<div className="table-wrap"><table><thead><tr><th>ASSET</th><th>CREDITED</th><th>FINALIZED DELIVERY</th><th>PENDING</th></tr></thead><tbody>{t.accrued.map((r:Data)=><tr key={r.asset}><td><strong>{symbol(r.asset)}</strong></td><td>{units(r.credited,decimals(r.asset))}</td><td>{units(r.paid,decimals(r.asset))}</td><td>{units(r.pending,decimals(r.asset))}<small>Current price unavailable</small></td></tr>)}</tbody></table></div>:<Empty title="No rewards credited yet" text="The first round needs verified fee receipts, five eligible assets and a complete holder snapshot."/>}
 <Epochs items={data.epochs.items} onOpen={async(id:string)=>{setEpoch(await api('epochs/'+encodeURIComponent(id)));}}/>{epoch&&<EpochDetail epoch={epoch} receiptLink={receiptLink}/>}
 <section className="note-panel"><h3>Small rewards stay yours.</h3><p>Accrued units carry forward without expiry. Delivery normally starts at $1 per asset with an existing token account, or $5 and at least three times the creation cost for a new account. Stale prices defer delivery.</p></section></>}
 {tab==='wallet'&&<><section className="page-heading"><div className="eyebrow">YOUR PUBLIC ADDRESS IS ALL YOU NEED</div><h1>Your share, clearly<span>.</span></h1><p>Check eligibility and credited rewards. No wallet connection or signature.</p></section><form className="wallet-form" onSubmit={search}><label htmlFor="address">Solana wallet address</label><div><input id="address" value={wallet} onChange={e=>setWallet(e.target.value)} placeholder="Paste your public wallet address" autoComplete="off" spellCheck={false} required maxLength={44}/><button className="primary-button" disabled={searching}>{searching?'Looking up…':'View rewards →'}</button></div></form>{lookupError&&<p className="notice error" role="alert">{lookupError}</p>}{lookup?<><div className="lookup-status"><span className="badge">{lookup.eligibility?.eligible?'ELIGIBLE AT SNAPSHOT':lookup.snapshotSlot?'NOT ELIGIBLE AT LAST SNAPSHOT':'NO SNAPSHOT YET'}</span><p>{lookup.reason??'Eligibility is based on the recorded balance at the start of an epoch.'}</p><code>{lookup.address}</code></div>{lookup.entitlements.length?<div className="table-wrap"><table><thead><tr><th>ASSET</th><th>CREDITED</th><th>PAID</th><th>PENDING</th></tr></thead><tbody>{lookup.entitlements.map((r:Data)=><tr key={r.asset}><td>{symbol(r.asset)}</td><td>{units(r.credited,decimals(r.asset))}</td><td>{units(r.paid,decimals(r.asset))}</td><td>{units(r.pending,decimals(r.asset))}<small>Price unavailable</small></td></tr>)}</tbody></table></div>:<Empty title="No credited rewards for this address" text="Accrued rewards will appear here after a funded epoch completes its purchase accounting."/>}{lookup.deliveries.map((r:Data)=><div className="receipt-row" key={r.id}><span>{symbol(r.asset)} <span className="badge">{r.status}</span></span>{receiptLink(r.result)}</div>)}</>:<Empty title="Rewards without wallet permissions" text="We only read public records. Holding EMBER5 never gives this service permission to spend assets in your wallet."/>}<section className="note-panel"><h3>How eligibility works</h3><p>At least 100,000 project tokens, aggregated across your token accounts, at the finalized epoch snapshot. Excluded project and system wallets do not participate. Selling affects future snapshots; existing credits remain owed. This is a balance snapshot, with no hold-duration protection.</p></section></>}
 {tab==='transparency'&&<><section className="page-heading"><div className="eyebrow">THE RULES AND THE RECEIPTS</div><h1>Nothing behind the numbers<span>.</span></h1><p>Inspect the policy, treasury accounts and the evidence for each round.</p></section><div className="notice"><strong>EMBER5 is a working name.</strong> Another independent project uses this name. This application is not connected to its token. Branding must be resolved before launch.</div><div className="lower-grid"><article className="state-panel"><div className="eyebrow">PUBLIC IDENTITY</div><dl><div><dt>Project mint</dt><dd className="break">{p.mint??'Contract not deployed'}</dd></div><div><dt>Treasury</dt><dd className="break">{p.treasury??'Not configured'}</dd></div><div><dt>Operations</dt><dd className="break">{p.operations??'Not configured'}</dd></div><div><dt>Accounting health</dt><dd>{t.accountingHealth.replaceAll('_',' ')}</dd></div></dl></article><article className="state-panel"><div className="eyebrow">PILOT POLICY</div><dl><div><dt>Budget split</dt><dd>80 / 10 / 10</dd></div><div><dt>Basket</dt><dd>Five assets · 20% each</dd></div><div><dt>Slippage / price impact cap</dt><dd>1% / 2%</dd></div><div><dt>Direct cost forecast cap</dt><dd>10% of funding</dd></div><div><dt>Snapshot eligibility</dt><dd>100,000 units</dd></div></dl><details><summary>Full versioned policy</summary><pre>{JSON.stringify(p.policy,null,2)}</pre></details></article></div>
 <div className="section-title"><h2>Per-asset accounts</h2><span className="muted">Raw units are never summed across assets</span></div>{t.balances.length?<div className="table-wrap"><table><thead><tr><th>ASSET</th><th>ACCOUNT</th><th>RAW UNITS</th></tr></thead><tbody>{t.balances.filter((r:Data)=>!r.account.startsWith('external:')).map((r:Data)=><tr key={r.asset+r.account}><td>{r.asset==='SOL'?'SOL':symbol(r.asset)}</td><td className="break">{r.account}</td><td className="mono">{r.amount}</td></tr>)}</tbody></table></div>:<Empty title="No treasury accounting activity" text="Recognized revenue, reserves and holder obligations will be recorded separately for each asset."/>}
 <Epochs items={data.epochs.items} onOpen={async(id:string)=>setEpoch(await api('epochs/'+encodeURIComponent(id)))}/>{epoch&&<EpochDetail epoch={epoch} receiptLink={receiptLink}/>}
 <section className="note-panel"><h3>Exclusions & custody</h3><p>{p.policy.exclusions.length?p.policy.exclusions.map((x:Data)=>x.owner+' — '+x.reason).join('; '):'No launch exclusions configured yet. Treasury, operations, team and verified pool vaults must be published before a funded round.'}</p><p>Eligible custodial owners receive rewards at their recorded owner address; beneficial ownership is not inferred. Off-curve addresses are not excluded automatically. Undisclosed insider wallets cannot be reliably identified.</p></section></>}
 </>}
 <footer><span className="footer-brand">EMBER5 <span> / INDEPENDENT REWARD EXPERIMENT</span></span><p>{p?.disclosure??'Rewards depend on received creator fees. The service controls the reward treasury.'}</p><p>No guaranteed returns. No redemption right. No official Ember affiliation.</p></footer></div></main></div>;
}
function Empty({title,text}:{title:string;text:string}){return <div className="empty-state"><span className="empty-glyph">—</span><h3>{title}</h3><p>{text}</p></div>}
function Epochs({items,onOpen}:{items:Data[];onOpen:(id:string)=>void}){return <section><div className="section-title"><h2>Epoch history</h2><span className="muted">Reproducible accounting records</span></div>{items.length?<div className="table-wrap"><table><thead><tr><th>EPOCH</th><th>STATUS</th><th>CREATED</th><th>RECORD</th></tr></thead><tbody>{items.map(e=><tr key={e.id}><td className="mono">{e.id}</td><td><span className="badge">{e.status}</span><small>{e.reason}</small></td><td>{time(e.created_at)}</td><td><button className="text-button" onClick={()=>onOpen(e.id)}>Inspect →</button></td></tr>)}</tbody></table></div>:<Empty title="The first epoch is still ahead" text="There are no completed rounds to display. Successful purchases and payouts will appear only when supported by verified evidence."/>}</section>}
function EpochDetail({epoch,receiptLink}:{epoch:Data;receiptLink:(r:Data)=>React.ReactNode}){return <section className="note-panel"><div className="section-title"><h3>{epoch.epoch.id}</h3><div className="export-links"><a href={'/api/epochs/'+encodeURIComponent(epoch.epoch.id)+'/export'} target="_blank" rel="noreferrer">JSON ↗</a><a href={'/api/epochs/'+encodeURIComponent(epoch.epoch.id)+'/export?format=csv'}>CSV ↓</a></div></div><p>{epoch.testOnly?'Test/demo record. ':''}Snapshot slot {epoch.snapshot.slot} · {epoch.entitlements.length} credited owner/asset rows</p><code className="break">Snapshot hash: {epoch.snapshot.hash}</code>{[...epoch.intents,...epoch.transfers.map((i:Data)=>({...i,kind:'holder payout'}))].map((i:Data)=><div className="receipt-row" key={i.id}><span>{i.kind} <span className="badge">{i.status}</span></span>{receiptLink(i.result)}</div>)}</section>}
createRoot(document.getElementById('root')!).render(<App/>);
