import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {PublicOverview} from '../../packages/shared/public.js';
import {api,assertOverview,routeFromHash,routes,type Route} from './view-model.js';
import {Allocation,Brand,Icon,Intro} from './components.js';
import {MarketPanel} from './market.js';
import {Rewards,Transparency,Wallet} from './records.js';
import './style.css';

function App(){
 const [route,setRoute]=useState<Route>(()=>routeFromHash(location.hash));const [data,setData]=useState<PublicOverview>();const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [menu,setMenu]=useState(false);
 async function reload(){try{const overview=assertOverview(await api<PublicOverview>('overview'));setData(overview);setError('');}catch(e){setError((e as Error).message);setData(current=>current?{...current,discovery:{...current.discovery,status:'stale',message:'Refresh failed. Showing the previous real observation.'},selection:{...current.selection,commitmentsAllowed:false}}:undefined);}finally{setLoading(false);}}
 useEffect(()=>{void reload();const interval=setInterval(reload,60000);return()=>clearInterval(interval);},[]);
 useEffect(()=>{function routeChanged(){if(location.hash==='#main'){document.getElementById('main')?.focus();return;}setRoute(routeFromHash(location.hash));setMenu(false);window.scrollTo({top:0,behavior:'instant'});}addEventListener('hashchange',routeChanged);return()=>removeEventListener('hashchange',routeChanged);},[]);
 useEffect(()=>{document.title=`EMBER10 — ${routes[route]}`;},[route]);
 const nav=(mobile=false)=>(Object.entries(routes) as [Route,string][]).filter(([key])=>mobile?!['transparency','how'].includes(key):key!=='how').map(([key,label])=><a key={key} href={`#${key}`} aria-current={route===key?'page':undefined} className={`nav-item ${route===key?'active':''}`}><Icon name={key}/>{label}{!mobile&&key==='basket'&&<span className="nav-count">10</span>}</a>);
 return <><a className="skip" href="#main">Skip to content</a><aside className="sidebar"><Brand/><div className="nav-label">Your Ember basket</div><nav className="navigation" aria-label="Main navigation">{nav()}</nav><div className="sidebar-bottom"><div className="ecosystem"><strong>Built around Ember.</strong><p>An independent rewards project<br/>on Solana.</p></div><div className="tiny-links"><a href="https://embercurve.fun/" target="_blank" rel="noopener noreferrer">Explore Ember ↗</a><span>PRELAUNCH</span></div></div></aside><div className="workspace"><header className="topbar"><Brand mobile/><div className="crumb"><span>Ember ecosystem</span><span>›</span><b>{routes[route]}</b></div><div className="top-actions"><span className="pill gold"><i className="dot"/>Prelaunch</span><a className="btn small desktop-action" href="#wallet"><Icon name="wallet"/>Check rewards</a><div className="mobile-menu"><button aria-label={menu?'Close navigation menu':'Open navigation menu'} aria-expanded={menu} aria-controls="mobile-menu-links" className="menu-button" onClick={()=>setMenu(!menu)}><Icon name={menu?'close':'menu'}/></button>{menu&&<nav id="mobile-menu-links" aria-label="More navigation"><a href="#transparency" onClick={()=>setMenu(false)}><Icon name="transparency"/>Transparency</a><a href="#how" onClick={()=>setMenu(false)}><Icon name="how"/>How it works</a></nav>}</div></div></header><main id="main" tabIndex={-1}>
 {error&&<div className="connection-error" role="alert"><span><strong>Refresh unavailable.</strong> {data?'Showing the last real observation.':error}</span><button className="btn small" onClick={()=>void reload()}>Retry</button></div>}
 {route==='overview'&&<><section className="hero"><div className="hero-copy"><div className="eyebrow">The Ember ecosystem, together.</div><h1>One token.<span>The Ember ten.</span></h1><p>Creator fees buy ten leading Ember tokens.<br className="desktop-break"/> Eligible holders receive their share.</p><div className="hero-actions"><a className="btn primary" href="#basket">Explore the ten <Icon name="arrow"/></a><a className="btn ghost" href="#how">How rewards work <Icon name="external"/></a></div><p className="hero-foot"><Icon name="transparency"/>No staking. No wallet permissions.</p></div><div className="ten-art" role="img" aria-label="Basket policy: ten equal purchase budgets, 10 percent each"><span className="art-caption">One basket. Ten possibilities.</span><span className="art-number" aria-hidden="true">10</span><div className="ten-grid" aria-hidden="true">{Array.from({length:10},(_,i)=><span className="ten-cell" key={i}>{String(i+1).padStart(2,'0')}</span>)}</div><span className="art-foot">10 equal purchase budgets · 10% each</span></div></section><section className="policy-strip" aria-label="Proposed basket policy">{[['Reward assets','10','target basket size'],["Each asset’s weight",'10%','of basket budget'],['Fees for rewards','80%','after direct costs']].map(([label,value,note])=><div className="policy-stat" key={label}><span className="label">{label}</span><strong>{value}<small>{note}</small></strong></div>)}</section><div className="section-heading"><div><h2>The market, in focus.</h2><p>See the ranking. Understand the selection.</p></div><a className="link-inline" href="https://embercurve.fun/markets" target="_blank" rel="noopener noreferrer">Source: Ember <Icon name="external"/></a></div><MarketPanel data={data} loading={loading} error={error} retry={()=>void reload()}/><div className="lower-grid"><Allocation/><article className="panel"><div className="eyebrow muted">Next reward round</div><h3>Ready when the checks are.</h3><div className="round-state"><div className="empty-icon"><Icon name="clock"/></div><div><strong>{data?`${data.selection.selectedCount} of 10 assets selected`:'Selection unavailable'}</strong><small>{data?'New purchase commitments blocked':'Selection data unavailable'}</small></div></div><p>{data?.selection.reason??'A verified selection and real funding are required before purchases begin.'}</p><a className="link-inline panel-link" href="#rewards">Follow the rewards <Icon name="arrow"/></a></article></div></>}
 {route==='basket'&&<><Intro eyebrow="Ten assets. One clear policy." title="The Ember ten." text="Ranked by market cap. Selected by published rules. Market observations and a funded reward basket are always shown separately."/><MarketPanel data={data} loading={loading} error={error} retry={()=>void reload()}/></>}
 {route==='rewards'&&<Rewards data={data}/>}{route==='wallet'&&<Wallet data={data}/>}{route==='transparency'&&<Transparency data={data}/>}
 {route==='how'&&<><Intro eyebrow="A simple idea. A visible process." title="Hold one. Receive from ten." text="Rewards depend on received creator fees. Holding EMBER10 does not guarantee a return or ownership of a redeemable fund."/><div className="rule-list">{[['01 / FUND','Fees arrive.','Verified creator fees enter the treasury. Direct execution costs and existing obligations are accounted for first.'],['02 / BUY','Ten budgets. Ten assets.','80% of net new creator fees funds equal purchases of ten eligible Ember tokens. All ten must pass the policy before new commitments.'],['03 / DISTRIBUTE','Holders receive their share.','Actual acquired units are credited by eligible snapshot balance. Small rewards accumulate until economical to deliver.']].map(([number,title,text])=><article className="panel" key={number}><span className="rule-index">{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div><article className="panel how-dev"><h3>What does the developer earn?</h3><p>The last 10% covers operations and developer compensation. Only the available OPS/DEV remainder after recorded costs, obligations and retained reserves may be paid to a configured receiving wallet. Holder rewards and buyback funds stay separate.</p><a className="link-inline panel-link" href="#transparency">Inspect the complete split <Icon name="arrow"/></a></article></>}
 <footer className="footer"><div><p>Independent project. No official Ember affiliation. Rewards depend on received creator fees; the project controls the reward treasury. No guaranteed returns or redemption right.</p><p className="contract-state">{data?.project.mint?'Contract configured · verification pending':'Contract not deployed'}</p></div><a href="#transparency">Rules & transparency ↗</a></footer></main></div><nav className="mobile-nav" aria-label="Mobile navigation">{nav(true)}</nav></>;
}
createRoot(document.getElementById('root')!).render(<App/>);
